#!/bin/bash 
adb shell screencap -p /sdcard/ScreenShot1.png
adb pull /sdcard/ScreenShot1.png
mv ScreenShot1.png ~/Desktop
adb shell rm /sdcard/ScreenShot1.png
#ad/Users/ammarmohamed/Documents/Scripts/Screenshot1.png\